name: MultiContainer Setup
on:
  push:
    branches: 
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Debug Client Directory
        run: ls -R ./client

      - name: build and test docker image
        run: docker build -t g0karki/react-test -f ./client/Dockerfile.dev .
      - name: Test my docker image
        run: docker run -e CI=true g0karki/react-test npm test